UPDATE Governorates SET ImageURL = 'https://res.cloudinary.com/dcctg0emo/image/upload/v1782855168/h4zpnpv26okfogjscrw2.jpg' WHERE Name = 'Cairo';
UPDATE Governorates SET ImageURL = 'https://res.cloudinary.com/dcctg0emo/image/upload/v1783020572/jihxqmjeyh6mpgjypova.jpg' WHERE Name = 'Giza';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Alexandria';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Luxor';
UPDATE Governorates SET ImageURL = 'https://res.cloudinary.com/dcctg0emo/image/upload/v1782855081/dipbtzn9bnhjl8ja1qqc.jpg' WHERE Name = 'Aswan';
UPDATE Governorates SET ImageURL = 'https://res.cloudinary.com/dcctg0emo/image/upload/v1782844703/sa706u80egd2k1774bvn.jpg' WHERE Name = 'Red Sea';
UPDATE Governorates SET ImageURL = 'https://res.cloudinary.com/dcctg0emo/image/upload/v1782844600/ogxvefpccwddeivuog39.jpg' WHERE Name = 'South Sinai';
UPDATE Governorates SET ImageURL = 'https://res.cloudinary.com/dcctg0emo/image/upload/v1783024013/y72neyo5y6eirvypbr4j.jpg' WHERE Name = 'Matrouh';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Fayoum';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Dakahlia';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Sharqia';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Qalyubia';
UPDATE Governorates SET ImageURL = 'https://res.cloudinary.com/dcctg0emo/image/upload/v1782930858/rdz74envavcgnvcyuxle.jpg' WHERE Name = 'Kafr El Sheikh';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Gharbia';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Monufia';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Beheira';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Beni Suef';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Minya';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Asyut';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Sohag';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Qena';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Damietta';
UPDATE Governorates SET ImageURL = 'https://res.cloudinary.com/dcctg0emo/image/upload/v1783019765/oaybbuqv0rvffc3ejvpt.jpg' WHERE Name = 'Port Said';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Suez';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'Ismailia';
UPDATE Governorates SET ImageURL = 'https://res.cloudinary.com/dcctg0emo/image/upload/v1783019712/fodo9btlqb4hqwzjdl8l.jpg' WHERE Name = 'North Sinai';
UPDATE Governorates SET ImageURL = NULL WHERE Name = 'New Valley';
