<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Kemora.Domain\Kemora.Domain.csproj" />
		<ProjectReference Include="..\Kemora.Application\Kemora.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="CloudinaryDotNet" Version="1.28.0" />
		<PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />

		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />

		<PackageReference Include="MimeKit" Version="4.17.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />

		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Data\" />
		<Folder Include="Services\" />
	</ItemGroup>

</Project>